recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LebjcgSAAAAANJ87hn9GVVSXlrxsKigZ98yFk2T"
	privateKey = "6LebjcgSAAAAAJYMTgSsLyt4KZqAmk62b0WwTEpY"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = "6LebjcgSAAAAANJ87hn9GVVSXlrxsKigZ98yFk2T"
    privateKey = "6LebjcgSAAAAAJYMTgSsLyt4KZqAmk62b0WwTEpY"
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}
